name: Deploy
on:
  workflow_run:
    workflows:
    - "Run Tests"
    branches:
    - main
    types:
    - completed

jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true

    - name: Build
      run: pnpm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: .vuepress/dist/
