name: Run Tests
on:
  push:
    branches-ignore:
    - gh-pages
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.27.0
        run_install: true

    - uses: xt0rted/markdownlint-problem-matcher@v2

    - name: Lint
      run: pnpm run lint

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.27.0
        run_install: true

    - name: Spellcheck
      run: pnpm run spellcheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.27.0
        run_install: true

    - name: Build
      run: pnpm run build
