name: Run Tests
on:
  push:
    branches-ignore:
    - gh-pages
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: lint-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          lint-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true

    - uses: xt0rted/markdownlint-problem-matcher@v1

    - name: Lint
      run: pnpm run lint

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: spellcheck-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          spellcheck-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true

    - name: Spellcheck
      run: pnpm run spellcheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true

    - name: Build
      run: pnpm run build
